modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/TeamLapen/Vampirism/issues"

[[mods]]
    modId="vampirism"
    namespace="vampirism"
    version="${version}"
    displayName="Vampirism"
    authors="Maxanier, Cheaterpaul"
    credits="TinkerHatWill (textures), Alis (textures), dimensionpainter (textures), S_olace (textures), Mistadon (code/models), wildbill22 (code), LRA_10 (models/textures), freesound.org (sounds), freeSFX.co.uk (sounds)"
    description="Allows you to become a vampire"
    displayURL="https://vampirism.maxanier.de"
    logoFile="logo.png"
    updateJSONURL="https://maxanier.de/projects/vampirism/versions.json"
    [[dependencies.vampirism]]
        modId="forge"
    mandatory = true
    versionRange = "[${forge_version},)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.vampirism]]
modId = "teamlapenlib"
mandatory = true
versionRange = "[${version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.vampirism]]
modId = "guideapi-vp"
mandatory = false
versionRange = "[${guideapi_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.vampirism]]
modId = "jei"
mandatory = false
versionRange = "[${jei_version},)"
ordering = "AFTER"
side = "BOTH"
[[mods]]
modId = "teamlapenlib"
namespace = "teamlapenlib"
version = "${version}"
displayName = "Teamlapen Library"
authors = "Maxanier, Cheaterpaul"
description = "Required by Vampirism"
displayURL = "https://vampirism.maxanier.de"
[[dependencies.teamlapen-lib]]
modId = "forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"